### ISSUE TITLE
Unable to spend from contract using dApp on Ropsten network

### ISSUE THREAD

**Issue by dhruvbansal** [unchained-capital/ethereum-multisig#3]
(This issue was originally reported by Calin Ciobanu via an email.)

I am trying to use the dapp from https://github.com/unchained-capital/ethereum-multisig on the Ropsten test network and all worked well until spending funds from the multisig. The transaction is initiated with 0 ETH from the GAS address TO the CONTRACT address.

![image](https://user-images.githubusercontent.com/6796/42333347-1e6576b0-8040-11e8-91aa-f1d54495435a.png)

Contract address: `0xfd052a54073a2ab1f24789cb35684f29f03b93a1`
Gas Address: `0xb28534Caba5e3D527cddF5e112bb3A683CDFDD4d`
To Address: `0xd31D56F6dA9E42E877E12741958035D36a132583`

Transaction looks like:

https://ropsten.etherscan.io/tx/0xae7dad362844c7e9afe3649b25baf86b6925ece30822d54673674db2bb1182c5

![image 1](https://user-images.githubusercontent.com/6796/42333388-37b88ddc-8040-11e8-895c-a5a727e45272.png)

**Comment by destrys** [comment]
Calin,
Could you provide as much of the follow as you are able?

**What is your environment?**
- Operation system & version: [Windows 10, Mac OS 10.11.6, Ubuntu 16.04]
- Ethereum node & version: [Parity 1.11.5, Geth 1.8.11, MetaMask 4.8.0]
- Hardware wallet & version: [Trezor ONE 1.5.2, Ledger Nano S 1.4.2]
- (If reporting a dApp bug) Browser & version: [Chrome 67.0.3396.99, Firefox 60.0.2, Safari 11.1.1]

I suspect this is due to this:
https://github.com/trezor/trezor-mcu/commit/1f470cf1f18de0235675cf71091bba7bf4fb762f
which was added in firmware v1.6.2 
This actually breaks the functionality of this contract, so for now you'll need to downgrade the trezor firmware to v1.6.1

We are working on an update to the dapp and contract that will address this, (assuming it's the culprit here)
